# .NET Desktop
# Build and run tests for .NET Desktop or Windows classic desktop solutions.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/apps/windows/dot-net

trigger:
- master

pool:
  vmImage: 'windows-latest'

variables:
  solution: '**/*.sln'
  buildPlatform: 'any cpu'
  buildConfiguration: 'Release'
  major: 3
  minor: 0
  Build: $[counter(variables['minor'], 0)]
  VersionNumber: $(major).$(minor).$(Build)

steps:

- bash: echo $(Build)



- task: DotNetCoreCLI@2
  inputs:
    command: 'restore'
    feedsToUse: 'select'

- task: DotNetCoreCLI@2
  inputs:
    command: 'build'
    projects: '**/SharpFluids5.csproj'



- task: DotNetCoreCLI@2
  inputs:
    command: 'pack'
    packagesToPack: '**/SharpFluids5.csproj'
    includesymbols: true
    includesource: true
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'VersionNumber'


- task: NuGetToolInstaller@1
  inputs:
    versionSpec: 
    checkLatest: true

- task: NuGetCommand@2
  inputs:
    restoreSolution: '$(solution)'

- task: VSBuild@1
  inputs:
    solution: '$(solution)'
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: VSTest@2
  inputs:
    platform: '$(buildPlatform)'
    configuration: '$(buildConfiguration)'


- task: NuGetCommand@2
  inputs:
    command: 'pack'
    packagesToPack: '**/SharpFluids.csproj'
    versioningScheme: 'byEnvVar'
    versionEnvVar: 'VersionNumber'
    includeSymbols: true
    buildProperties: '-IncludeReferencedProjects'



- task: NuGetCommand@2
  inputs:
    command: 'push'
    packagesToPush: '$(Build.ArtifactStagingDirectory)/**/*.nupkg;!$(Build.ArtifactStagingDirectory)/**/*.symbols.nupkg'
    nuGetFeedType: 'external'
    publishFeedCredentials: 'NuGet.org'
    includeNugetOrg: true